src/webpack.js
test/crypto-browserify.test.js
test/fixtures/crypto-browserify.js
yarn.lock

The native crypto is more reliable.

Use crypto instead of crypto-browserify in Lambda bundles

---

package.json
yarn.lock

Upgrade aws-sdk

---

src/graphql.js
test/graphql-assertions.test.js

Add path to assertSuccess error output string

---

src/lambda.js
test/lambda-tools-container-zipfile.test.js

When running integration tests inside docker, and launching new docker instances from inside, extra control is needed over the unzip path so that a directory that exists both inside and outside the container can be picked

Allow picking the directory that Lamabda zips are unzipped into

---

package.json
src/dynamodb.js
test/dynamodb.test.js
yarn.lock

* test table creation/deletion
* wait for tableExists/tableNotExists states after creating/deleting a table
* increase dynamodb request timeout

Fix intermittent create tables failures

---

src/dynamodb.js
test/dynamodb-custom-endpoint.test.js
test/dynamodb-wait-for-ready.test.js
test/dynamodb.test.js

Improvements:
- Log any creation/deletion errors
- Only attempt to destroy tables that were successfully provisioned

improve create and destroy tables error reporting

---

src/dynamodb.js
src/kinesis.js
test/kinesis/basic-parallel.test.js
test/kinesis/basic-serial.test.js
test/kinesis/custom-endpoint.test.js
test/kinesis/kinesis.test.js
test/kinesis/testHooks-error.test.js
test/kinesis/wait-for-ready.test.js

Add LocalStack Kinesis docker for tests

---

package.json

Version Bump 8.1.0

---

.travis.yml
package.json
src/dynamodb.js
src/index.d.ts
src/kinesis.js
src/utils/awsUtils.js
test/dynamodb/basic-parallel.test.js
test/dynamodb/basic-serial.test.js
test/dynamodb/custom-endpoint.test.js
test/dynamodb/dynamodb.test.js
test/dynamodb/testHooks-error.test.js
test/dynamodb/wait-for-ready.test.js
test/kinesis/kinesis.test.js
test/kinesis/testHooks-error.test.js
yarn.lock

Allow for external configuration of the http client.  Delete tables if create fails so further tests don't fail on create. Update typescript interface

Fix issues where timeouts need to be extended

---

src/index.d.ts
src/localstack.js

Fix sqs port.  For some reason the advertised port does not get opened

---

package.json
src/index.d.ts

Note that this patch is required to begin using the new `inMemory` feature from 8.4.0.

Fix implicit any errors in index.d.ts

---

src/lambda.d.ts
src/lambda.js

Fixed the useLambdaHooks options interface

---

src/dynamodb.d.ts
src/dynamodb.js
test/dynamodb/dynamodb.test.js

Allow some retries

---

README.md
src/dynamodb.js
src/kinesis.js
src/localstack.js
src/utils/config.d.ts
src/utils/config.js
test/utils/config.test.js

Add p-queue for kinesis and dynamodb. Configure using env variable

---

CHANGELOG.md
src/lambda.d.ts

I'm invoking the build directly from TypeScript code.

Fix webpackoptions type

---

src/graphql.js
test/graphql-query.test.js

This change is needed to support this kind of tests: https://bitbucket.org/lifeomic/patient-service/pull-requests/561/lx-2855-prevent-issues-with-ctxstate

LX-2855: add support for batch requests to graphql helper

---

tsconfig.json

Didn't run tsc before.

---

test/localstack/lambdaSetup.test.js
test/utils/kinesisTools.test.js

Something about the lambci docker image changed, and now it appears unable to get credentials from its self.

Add credentials to the ENV for the lambda image

---

src/kinesis.js

Lock version of docker images

---

package.json
yarn.lock

Updated typescript and babel to support new ts features

---

CHANGELOG.md

Updating changelog before version release

---

src/localstack.ts

Fixes https://github.com/lifeomic/lambda-tools/security/code-scanning/5?query=ref%3Arefs%2Fheads%2Fmaster

[CON-1241] globally remove \r in chunks [codeql]

---

CHANGELOG.md
package.json
test/lambda/runtime-promises.test.js

Releasing new version

---

CHANGELOG.md
README.md
package.json
src/dynamodb.ts
test/dynamodb/dynamodb.test.js

I'm getting strange failures from the dynamodb image.  I don't see any reason why not to use the official docker image provided by Amazon.

Specify dynamodb image and version.

---

package.json
src/docker.ts
test/docker/pullImage.test.js

This is tricky to fully test without pushing out a pre-build due to the nature of working with jenkins.  So I'll just do a final test on a dependent project/build once this is merged and look for the proper logging in the tests.

CR-977: Adding dockerhub cred handling

---

.github/workflows/release.yaml
README.md

Get coverage report, and update badges

---

src/localstack.ts
test/localstack/version12Status.test.js

convenience method for those not using the auto setup for localstack.  I generally use something now to wait for localstack to set up in docker compose.

Expose a simple is ready endpoint

---

package.json

Release new minor version

---

package.json
src/docker.ts
test/docker/pullImage.test.js

[Dockerode](https://github.com/apocas/dockerode/blob/ad8f7a083458036d155658a45cbf3ad453605a14/lib/docker.js#L90) wants the auth settings in `opts.authconfig`

Docker auth config

---

.github/workflows/pr-build.yaml
package.json
src/graphql.ts
test/graphql/queryHooks.test.js

I need this to start using the beforeEach functionality in a Jest test.

Add graphql hooks for jest

---

package.json
src/graphql.ts
src/lambda.ts

Ran into some issues updating another project.

Enhance graphql types

---

package.json
src/lambda.ts
yarn.lock

This change points to the latest published `alpha` version.

fix: bump alpha version
