lifeomic/lambda-tools

- src/webpack.js
Before this change, some projects using this would fail with a failure like https://github.com/electron-userland/electron-webpack/issues/125.
Additionally, this string based syntax matches the documented style from https://www.npmjs.com/package/@babel/preset-env
> Use documented form of plugin reference

- README.md
- bin/build.js
- package.json
- src/handleWebpackResult.js
- src/webpack.js
- src/zip.js
- test/fixtures/multi-lambdas/func1.js
- test/fixtures/multi-lambdas/func2.ts
- test/fixtures/multi-lambdas/func3/index.js
- test/fixtures/multi-lambdas/func4/index.ts
- test/handleWebpackResult.test.js
- test/webpack-build.test.js
- yarn.lock
The code is now more flexible about entrypoints and creating zip files for each. Before my change there was a limitation that did not allow you to use the `-z` option if more than one entrypoint is provided.
I decided to do our own zipping instead of using `ZipPlugin` for weback so that there is one code path for creating zip files.
Also, if an entrypoint is a directory then the directory is automatically expanded into multiple entrypoints by scanning the files in the directory.
> Allow multiple entrypoints to be provided and create zip files for each

- src/webpack.js
- test/webpack-build.test.js
This was causing my local environment to hang indefinitely for one of our builds.
> ignore previously output zip file for repeatibility

- README.md
The markdown wasn't quite right, resulting in the following:
<kbd>
</kbd>
> fix typo in readme - unique tables name format

- src/patches/dns.js
- test/fixtures/runtime_dns.js
Other shims and pollyfills may modify the native APIs after the
lambda-tools patches have been applied. This will break the
lambda-tools functionality since the expected attributes will no
longer be present.
> Do not set attributes on native functions in patches

- src/xray.js
this will give us the functionality to accommodate the conditional operators encountered in many cases by being able to return a captureAWS object from the aws-sdk
> add aws-sdk as parameter to xray helper

- src/patches/lambda.js
- test/fixtures/runtime_promises.js
- test/lambda-runtime-promises.test.js
The Lambda Node.js 8.10 runtime requires handler-returned promises
to be propper instances of the native Promise constructor. The
Node.js 6.10 runtime doesn't support handler-returned promises at
all. This change patches the runtime to use a more general
definition of a handler-returned promise that is also compatible
with the Node.js 6.10 runtime.
> More flexible promise support

- src/patches/lambda.js
- test/fixtures/runtime_callbacks.js
- test/lambda-runtime-callbacks.test.js
The AWS runtime protects against multiple callback invocations, but
does not warn when this happens. Returning multiple responses from
a Lambda function is often a sign of a bug. Logging provides a way
to detect this.
> Detect multiple callback invocations

- package.json
- src/webpack.js
- yarn.lock
In the changelog for uglify-webpack-plugin 2.x a breaking change is to drop support for ES6. They suggest moving to terser-webpack-plugin. The change was simple and didn't seem to break anything.
I've bumped the major version since it has such potential for harm, but I'm cautiously optimistic.
> Switch to terser

- README.md
- package.json
- src/index.js
- src/mockServerLambda.js
- test/mockServerLambda.test.js
- yarn.lock
These APIs were extracted from the patient-service integration tests so that they can be more easily shared.
> Add APIs to mock Lambda function invocation based on MockServer

- src/dynamodb.js
Some people like using frameworks other than Ava for testing, so we should expose a test framework independent set of hooks.  People who are using Jest should be able to use the `dynamoDBTestHooks` helper to setup their tests
> Expose DynamoDB test hooks that are not dependent on Ava

- src/docker.js
User namespases are not compatible with the docker host network.
See https://docs.docker.com/engine/security/userns-remap/
> Disable namespace remapping when getting host address

- README.md
- bin/build.js
- package.json
- src/webpack.js
- test/fixtures/lambda-with-tsconfig/index.ts
- test/fixtures/lambda-with-tsconfig/tsconfig.json
- test/webpack-build.test.js
- yarn.lock
When the `--tsconfig` argument is specified, the webpack configuration will use `ts-loader` to transpile TypeScript.
> Allow specifying custom tsconfig file

- src/docker.js
- test/docker-executeContainerCommand.test.js
- test/helpers/createDefaultContainer.js
Here is what inspectOutput looks like: 
{"ID":"6f52a413a767a674e4f7c6c6e386db358a8f63fd53b1e8edab64cc48918d65fe","Running":false,"ExitCode":0,"ProcessConfig":{"tty":false,"entrypoint":"node","arguments":["/opt/lifeomic/deploy/bin/launchSetupDatabase.js","global-stats-handler-test-db"],"privileged":false},"OpenStdin":false,"OpenStderr":true,"OpenStdout":true,"CanRemove":false,"ContainerID":"a68caf095d2c64217ceb4de596dd407ee8a020c7c7e012038e403c3503079baf","DetachKeys":"","Pid":57462}
This will allow us to verify successful execution of setupDatabase task in life-social-queries-service by checking the ExitCode
> Add inspect output to executeContainerCommand to be able to let clients check exit code

- src/webpack.js
- test/fixtures/typescript-es2017/async_test.ts
- test/fixtures/typescript-es2017/tsconfig.json
- test/webpack-build.test.js
TypeScript compilation can leave async/await calls in the code and those do no get handled correctly by X-Ray. This change removes those async/await calls
> Remove async/await calls after TypeScript transpilation

- bin/build.js
- src/webpack.js
- test/webpack-build.test.js
This allows people to turn off runtime source map support if low latency is a goal
> Allow opting out of runtime source map support

- bin/build.js
- src/webpack.js
- test/webpack-build.test.js
Skipping minification shave 66% off my Lambda build time and does not have a noticeable impact on cold start times.
> Add build option to skip minification

- src/patches/dns.js
- test/fixtures/runtime_dns.js
While debugging slow Lambda cold starts, it would be helpful to see if DNS lookup retries are the cause
> Log when DNS lookups are retried

- package.json
- yarn.lock
In 9c38cc1fcae5e9e7b1d57f5cef425ab9d664428d, Greenkeeper bumped from 1.0.5 to
2.0.0, which is [no longer available on NPM](https://www.npmjs.com/package/tmp-promise). This keeps me from installing the latest release of this project, `7.6.6`.
> Fix tmp-promise dependency version

- package.json
- src/graphql.js
- test/fixtures/runtime_dns.js
- test/graphql-assertions.test.js
- test/lambda-createLambdaExecutionEnvironment-errorHandling.test.js
- test/lambda-graphql.test.js
- yarn.lock
When people deploy to AWS Lambda, they often exclude uploading the aws-sdk package since the Lambda runtime already includes a copy. I've been doing this for a while now and this package works fine. The only minor problem is that npm can complain when trying for force all packages to use the Lambda aws-sdk version using "resolutions" in package.json because the this library claims to need a higher version.
I don't believe this package needs the higher version it claims to, and so reducing the package version will make it clear that this library is compatible with Lambda Node 8.10's builtin runtime.
> Expand aws-sdk version range to include Lambda Node 8.10 packaged version

- src/utils/awsUtils.js
> The httpOptions.timeout appears to be causing timeout issues with docker tests.

- src/dynamodb.js
- test/dynamodb/dynamodb.test.js
Looks like this was broken in commit a9af2be24ded23caeeff2fa29f4afe2bb743dc1b back in April. I was debugging another issue and noticed lots of duplicate/ever increasing table counts.
> Fix cleanup of unique table names

- src/kinesis.js
- test/kinesis/kinesis.test.js
Kinesis equivalent to https://github.com/lifeomic/lambda-tools/pull/133
Thanks @DavidTanner for pointing out that there was a similar issue with the stream cleanup.
> Fix cleanup of unique stream names

- .travis.yml
- src/dynamodb.js
- src/lambda.js
- test/dynamodb/dynamodb.test.js
- test/lambda/runtime-events.test.js
Timeout errors during creation and deletion should not be re-attempted, rather the tables should be monitored until the desired effect has occurred
> Handle timeouts in table creation and deletion gracefully

- .gitignore
- bin/build.js
- package.json
- src/webpack.js
- test/webpack-build.test.js
- yarn.lock
Changing some defaults that are more grief.  Also should speed up the build.
Minification causes builds to be very slow, and makes the resulting file difficult to debug. 
Updating to use 12.x as the default lambda since 8 and 10 are soon to be removed from AWS Lambda, and 6 is already gone.
Runtime maps is also another source of slowness that appears to be not as beneficial as hoped.
> Default changes

- package.json
- src/docker.d.ts
- src/kinesis.js
- src/lambda.d.ts
- src/lambda.js
- src/localstack.d.ts
- src/localstack.js
- test/lambda/core.test.js
- test/lambda/createLambdaExecutionEnvironment.test.js
- test/lambda/tools-container-compose-network.test.js
- test/lambda/tools-container-zipfile.test.js
- test/localstack/serviceStatus.test.js
- yarn.lock
As of right now, the latest tag for localstack doesn't launch elasticsearch.  Pinning the test to 0.10.6.
> Fix tests for elasticsearch in docker

- package.json
- src/webpack.js
- test/fixtures/async_iterators.js
- test/webpack-build.test.js
- yarn.lock
This change allows services to build against `es2019` as a target (while continuing to support x-ray) by converting async iterators into generator code
> Add support for async iterator compilation for lambdas

- src/dynamodb.js
- src/graphql.js
- src/kinesis.js
- src/lambda.js
- src/localstack.js
- test/graphql-config.test.js
- test/lambda/tools-container-compose-network.test.js
The setup steps should be done serially.  This allows downstream projects to do some configuration before kinesis/localstack/docker, and out of order issues won't happen accidentally
> Do setup steps predicatably

- .travis.yml
- README.md
- examples/compose/docker-compose.yaml
- package.json
- src/docker.js
- src/dynamodb.js
- src/handleWebpackResult.js
- src/kinesis.js
- src/lambda.js
- src/localstack.js
- src/utils/logging.d.ts
- src/utils/logging.js
- src/webpack.js
- test/docker/pullImage.test.js
- test/lambda/compose-container.test.js
- test/lambda/createLambdaExecutionEnvironment.test.js
- test/lambda/runtime-callbacks.test.js
- test/lambda/runtime-events.test.js
- test/localstack/getConnection.test.js
- test/localstack/lambdaSetup.test.js
- test/localstack/useLocalStack.test.js
- test/utils/logging.test.js
@Druotic and I were discussing using a standardized logger, possibly using bunyan and debug, but ultimately the logs won't be going through any processors so debug looks the best.  This just replaces all of the `console` commands with debug logs.  `info`, `warn`, and `error` will always print out to the console, with `debug` relying on the `DEBUG` environment variable being set.  
I will do a major release with approval.
> Logging lib

- src/lambda.d.ts
The raw query to AlphaClient accepts event and context, but only uses the event.
> Fix typing of the raw call to alpha

- src/dynamodb.js
- test/dynamodb/testHooks-error.test.js
I noticed in [v8.2.0](https://github.com/lifeomic/lambda-tools/pull/120), we started having issues with intermittent errors related to Dynamo. Originally, I thought there was something functionally wrong introduced in that version. But the root cause in my case ended up just being more frequent timeouts in the beforeAll hook. It seems something about that change made the beforeAll hook slower.
However, because of the way the default test runner for Jest ~works~is broken, there's no guarantee on the ordering of hooks should one fail. See https://github.com/facebook/jest/issues/8484
There are also comments down below with more details, but the TLDR was it made tracking down the cause significantly more difficult and in some cases and if not careful, could have deleted/corrupted entire …
> check config in beforeEach to prevent possibility of data corruption

- tsconfig.json
The module type needs to be commonjs or tsc will output `import` statements in the `.js` files.
> Missed the module specification

- CHANGELOG.md
- package.json
- tsconfig.json
- yarn.lock
More moving to `peerDependencies` - but in this case there `alpha` was being used without an explicit dependency entry in the package.json (other than a dev dependency). Updated the dev dependency just for testing purposes to ensure compatibility with the new version.
> Move `@lifeomic/alpha` to `peerDependencies`, bump dev version for compatibility testing

- .github/workflows/release.yaml
- package.json
I noticed that anytime a tag was created it was pushed to NPM.  This PR has the release build only run on a push to master, and then only publishes the lib if a git tag exists, and the npm.js version doesn't already exist.
> Fix export and release

- .github/workflows/release.yaml
- package.json
The release process creates a tag anyways, so why require the dev to do it.
> Fix release tag process

- package.json
- src/lambda.ts
This anonymous function declaration was causing downstream type errors on linting in new projects generated by our yo service generator tool.
> fixing downstream TS errors

- package.json
- src/webpack.ts
Fixing some downstream TS errors resulting from conflicting version of TS treating untyped arrays as `never[]` vs `any[]`. This PR just properly types the array that was causing issues downstream.
We should also look into _only publishing_ the .js files. The .ts source files are also getting published and it seems to be causing mild problems for newer repos created with the yo generator when they attempt to run `tsc`.
> fixing more downstream typescript errors.

- src/utils/kinesisTools.ts
In a future TS version (4.x), this line causes problems b/c the referenced values are non-nullable functions. Issues arise in consuming projects using that future TS operators.
I added these `!!` operators to satisfy the compiler without changing behavior.
More context: https://github.com/lifeomic/balance-service/pull/1#discussion_r633741487
> Fix future typescript issue

- bin/build.ts
- src/webpack.ts
Motivation: we found that typechecking with ts-loader doesn't work well OOTB. Connect-service has code that explicitly sets `transpile-only` using a webpack transformer. This allows you to set transpile-only on the build script itself which applies when using a tsconfig/ts-loader.
> Add a transpile-only option for use when using ts-loader (used when specifying a tsconfig)

- src/mockServerLambda.ts
See line 15 below. `requestBody` is supposed to be optional to allow ignoring.
> requestBody is optional

- bin/waitForLocalstack.ts
- package.json
- src/localstack.ts
- test/localstack/externalDocker.test.ts
- test/localstack/version10Status.test.js
- test/localstack/version12Status.test.js
- test/localstack/version13Status.test.js
Export a method to check if a docker instance of localstack has finished setting up.
It is fairly common to need to wait for localstack to be running before setting up lambda, creating dynamo tables, etc.  This let us wait till the service is actually ready before making calls, instead of a long pause and checking each service, which can cause localstack to crash.
> External Docker check for localstack availability

- .github/workflows/pr-build.yaml
- .gitignore
- package.json
- src/localstack.ts
- test/localstack/externalDocker.test.ts
- test/localstack/localstackNameTags.test.ts
- test/localstack/version14Status.test.ts
- yarn.lock
The external docker function was never closing for docker compose setups.  Once we get the `Ready.` message, we don't need to listen to the container anymore.
> Expand configuration, and fix localstack hang when waiting for docker

- .github/lifeomic-probot.yml
- .github/workflows/pr-build.yaml
- .github/workflows/release.yaml
- package.json
- release.config.js
- yarn.lock
Adopting semantic-release in this library.
Also, stop testing on Node 12. Why: the latest version of semantic-release requires Node 14.
I think it's okay to do this -- the package will still work on Node 12, we just won't necessarily fail CI if problems start happening on Node 12.
> Adopt semantic-release and Node 14

- .github/workflows/pr-build.yaml
- .github/workflows/release.yaml
- .gitignore
- build-package.js
- package.json
- release.config.js
- tsconfig.json
**NOTE**: this PR depends on #303.
This library has incorrectly published its `.ts` files for a _long_ time. This often unnecessarily causes compilation errors in downstream projects, especially when building. We should stop.
> Stop publishing source files

- tsconfig.json
Some pure JS files were removed from the `dist`, breaking the library.
> fix: add allowJs to re-include pure js files

- build-package.js
- tsconfig.json
With some of the recent changes the `patch` files end up having inlined source maps that don't get handled well when pasting those files in with the `WrapperPlugin`.  This fixes it by not explicitly compiling those but copying them over (this seems to match the previous behavior from looking at other outputs)
> fix: skip compilation of patch files because they cause issues when bundling

- bin/build.ts
- src/webpack.ts
I know this is _technically_ a br3aking change, but I consider it more of a critical bug fix. I'd like to force adopters to do this if upgrading at all, and not just if they do a major version bump.
> fix: don't use test-service as a service name default

- src/lambda.ts
- test/lambda/entrypoint.test.js
- Updated `getEntrypoint` method to remove unneeded `await` since `getImage` doesn't return a promise
- Also updated `getEntrypoint` to check `Config` property for endpoint if it is not present in `ContainerConfig`
This came about when I looked for a potential replacement for [lambci](https://github.com/lambci/lambci) since it appears to be abandoned and I found one called docker-lambda ([github](https://github.com/mLupine/docker-lambda) and [docker hub](https://hub.docker.com/r/mlupin/docker-lambda/tags?page=1&name=nodejs16)) which is forked from lambci, but when testing it out, I kept getting the error `The image ${imageName} has no entrypoint and no parent image`. I noticed that `Entrypoint` was undefined for `ContainerConfig`, but not for the `Config` prop
> No task/handle config entrypoint

- examples/dynamodb/package.json
I found this by running an analysis on all the package.json files in our organization. I'm surprised it hasn't been found before.
> Fix invalid JSON in examples/dynamodb/package.json

- src/lambda.ts
- test/lambda/entrypoint.test.js
- test/localstack/version13Status.test.js
While upgrading a repo I encountered this error, it seems that `ContainerConfig` is now [removed](https://docs.docker.com/engine/release-notes/26.0) in new docker clients.
> fix: Handle Missing ContainerConfig on Newer Docker Clients
